sonar.projectKey=usdot-fhwa-stol_message-validation-tool
sonar.organization=usdot-fhwa-stol

sonar.projectName=message-validation-tool
sonar.sources=.

sonar.python.version=3.10

sonar.exclusions=**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.json,**/__pycache__/**,.github/**

sonar.coverage.exclusions=**/*